### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by jbenet** [VictorBjelkholm/openipfs#14]
@VictorBjelkholm would you mind changing the name to something else? OpenIPFS is not good because:
- it implies IPFS is not open, but it is.
- it is not clear what this actually is (maybe use like `pinner, rehost, net, group, cluster`)
- should elucidate a particular group, distinct from other potentially similar groups.

some (meh...) suggestions:
- Andromeda
- Global Cluster
- OpenPin
- OpenPinner
- PinNet
- IPFSCoop / ipfscoop

**Comment by victorb** [comment]
Agree and absolutely something I would like to do!

Throwing in another suggestion, as a reminder to self: "IPFS-Swarm"

**Comment by ghost** [comment]
I like anything with ipfs and coop, and also pin-federation. Swarm is nice but will be confused with the swarm in IPFS' networking.

**Comment by harlantwood** [comment]
Open curation?  Federated curation?

**Comment by cryptix** [comment]
hivePin?

**Comment by victorb** [comment]
Thanks for the feedback! Something that was suggested by a friend after looking through the suggestions was "PinCoop" that kind of stuck with me. It's a cooperative that helps pin stuff.

Feels descriptive and catchy enough?

**Comment by harlantwood** [comment]
I think there is a .coop tld :)

On Wed, Nov 4, 2015, 1:09 PM ᴠɪᴄᴛᴏʀ ʙᴊᴇʟᴋʜᴏʟᴍ notifications@github.com
wrote:

> Thanks for the feedback! Something that was suggested by a friend after
> looking through the suggestions was "PinCoop" that kind of stuck with me.
> It's a cooperative that helps pin stuff.
> 
> Feels descriptive and catchy enough?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/VictorBjelkholm/openipfs/issues/14#issuecomment-153865962
> .
> 
> ## 

Harlan T Wood
EnlightenedStructure.net
It is my commitment to catalyze the creation and adoption of luminous tools
to enable free and open transformation of organizations, individuals, and
the world.  I dream of an age of enlightened creativity, and the end of
scarcity on planet Earth.

**Comment by ghost** [comment]
On 04.11.2015 22:14, Harlan T Wood wrote:

> I think there is a .coop tld :)

only for proper cooperatives though

**Comment by ghost** [comment]
So is it PinCoop? I like it :)

**Comment by victorb** [comment]
PinCoop it is indeed! Renaming is done :)
